services:
  web:
    build:
      context: .
      dockerfile: docker/development/nginx/Dockerfile
    ports:
      - "8080:80"
      - "8444:443"
    volumes:
      - .:/app
      - ../sevenstime-storage:/app/public/storage
    networks:
      - default
      - blockchain.dev
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/development/php-fpm/Dockerfile
      args:
        - HOST_UID=1000
        - HOST_GID=1000
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - ../sevenstime-storage:/app/public/storage
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
    volumes:
      - .:/app
      - ../sevenstime-storage:/app/public/storage
    networks:
      - default

  web-node:
    image: node:20.18.0
    working_dir: /app
    environment:
      - WEBPACK_DEV_SERVER_ALLOWED_HOSTS=${WEBPACK_DEV_SERVER_ALLOWED_HOSTS}
    volumes:
      - .:/app
      - ../sevenstime-storage:/app/public/storage
    command: sh -c "yarn install && yarn encore dev --watch"
    tty: true
    networks:
      - default

  sevenstime-node-server:
    build:
      context: .
      dockerfile: docker/development/node-server/Dockerfile
    volumes:
      - ./node-server:/app/node-server
      - ../sevenstime-storage:/app/public/storage
    networks:
      - default
      - blockchain.dev
      - sevens-exchanger-default
    environment:
      - NODE_ENV=development
      - SEVENS_TOKEN_IDL_PATH=${NODE_SERVER_SEVENS_TOKEN_IDL_PATH}
      - SEVENS_TOKEN_MANAGEMENT_IDL_PATH=${NODE_SERVER_SEVENS_TOKEN_MANAGEMENT_IDL_PATH}
      - ANCHOR_PROVIDER_URL=${ANCHOR_PROVIDER_URL}
      - NONCE_EXPIRATION_MIN=${NONCE_EXPIRATION_MIN}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - EXCHANGER_WEBSOCKET_URL=${EXCHANGER_WEBSOCKET_URL}
    extra_hosts:
      - "sevenstime.local:host-gateway"
      - "localhost:host-gateway"
    secrets:
      - db_password
    depends_on:
      - mysql
      - web
    container_name: sevenstime-node-server

  mysql:
    image: mysql:9.3
    environment:
      MYSQL_USER: app
      MYSQL_DATABASE: sevens-time
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3307:3306"
    volumes:
      - ./../.data/sevens:/var/lib/mysql
    secrets:
      - db_password
    networks:
      - default

secrets:
  db_password:
    file: ./docker/development/secrets/db_password
  mailer_password:
    file: ./docker/development/secrets/mailer_password
  sentry_dsn:
    file: ./docker/development/secrets/sentry_dsn
  jwt_encryption_key:
    file: ./docker/development/secrets/jwt_encryption_key
  jwt_public_key:
    file: ./docker/development/secrets/jwt_public_key
  jwt_private_key:
    file: ./docker/development/secrets/jwt_private_key
  backup_aws_secret_access_key:
    file: ./docker/development/secrets/backup_aws_secret_access_key

volumes:
  mysql-backup:
  backup-storage:

networks:
  blockchain.dev:
    external: true
    name: sevens.dev
  sevens-exchanger-default:
    external: true
    name: sevens-exchanger-default
