controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: en

home_redirect:
    path: /
    controller: App\Controller\LocaleRedirectController::redirect
